DROP TABLE IF EXISTS globals;
DROP TABLE IF EXISTS cases;
DROP TABLE IF EXISTS tags;
DROP TABLE IF EXISTS photos;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS location;
DROP TABLE IF EXISTS sporttypes;
DROP TABLE IF EXISTS sonstige_sporttypes;